plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    // Add this line to provide the proper names for Minecraft classes/methods:
    mappings loom.officialMojangMappings() 
    
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}


processResources {
    def version = project.version
    inputs.property "version", version
    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

java {
    withSourcesJar()
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}
