# Mod info
mod_version=1.0.0
maven_group=subham.itemfinder

# Minecraft / Fabric versions
# NOTE: 26.2 unobfuscated hai, isliye yarn_mappings ki zaroorat nahi hai ab
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16
fabric_version=0.153.0+26.2

# LibGUI version
libgui_version=17.0.0+26.2

# 26.2 ko Gradle JVM ke liye Java 25 chahiye
java_version=25
