# Mod info
mod_version=1.0.0
maven_group=subham.itemfinder

# Minecraft / Fabric versions (fabricmc.net pe latest matching set check karo)
minecraft_version=26.2
yarn_mappings=26.2+build.10
loader_version=0.15.11
fabric_version=0.92.2+26.2

# LibGUI version (LibGUI GitHub releases pe apne MC version se match karo)
libgui_version=9.2.1+26.2
